move common json-rpc bits to a library
acammack-r7/metasploit-framework pull request #3
Opened 2017-04-01 11:29 UTC by busterb

This moves the communication bits out of the module and into a library for the next module to use. It does make bridge a little less pure by including PYTHONPATH, I guess eventually we'll publish a real library external to metasploit that would eliminate the need for this being bundled in.

2017-04-01 15:28 UTC, acammack-r7 requested changes
I'd prefer another way to do it, but it's fine for now. We can avoid clobbering `PYTHONPATH`, though.

2017-04-01 15:28 UTC, acammack-r7 commented on lib/msf/core/modules/external/bridge.rb
> +      'PYTHONPATH' => File.expand_path('../python', __FILE__)
Probably shouldn't clobber the path.

2017-04-01 15:33 UTC, acammack-r7 commented
As a more general approach, I think we would subclass `Bridge` (`PyBridge`, `JBridge`, etc.) and add binfmt-style bridge choosing to the loader. It would then directly invoke `*Bridge.new(path)` and pass the resulting object to the shim. No need to do that for this PR, though.

2017-04-01 16:03 UTC, busterb commented on lib/msf/core/modules/external/bridge.rb
> +      'PYTHONPATH' => File.expand_path('../python', __FILE__)
ah, that sounds like the right way to go.

2017-04-03 02:04 UTC, busterb commented
I like your approach of subclassing bridge. Will close this and rework.

2017-04-03 02:04 UTC, closed without merging